version: "2"
services:
        orthanc:
                build: orthanc
                restart: unless-stopped
                ports: ["104:4242", "80:8042"]
                volumes: ["orthanc-storage:/var/lib/orthanc/db:Z"]
volumes:
        orthanc-storage:
